version: 2
executorType: machine
jobs:
  build:
    working_directory: $GOPATH/src/github.com/moby/tool
    steps:
      - checkout
      - run: go get github.com/golang/lint/golint
      - run: cd $GOPATH/src/github.com/moby/tool && make test